### ISSUE TITLE
Terms `management` and `transfers` are not declared as translatable

### ISSUE THREAD

**Issue by modreoci** [solidusio-contrib/solidus_i18n#12]
Terms `management` and `transfers` in `backend/app/views/spree/admin/shared/_stock_sub_menu.html.erb` are not declared as translatable.

**Comment by tvdeyen** [comment]
They should be, regarding to https://github.com/solidusio/solidus/blob/21038e667c60d6321ec98c566628e1681505dd65/backend/app/helpers/spree/admin/navigation_helper.rb#L18 the translation key needs to be:

```yaml
sk:
  spree:
    admin:
      tab:
        stock_items: ...
        stock_transfers: ...
```
