### ISSUE TITLE
German number.percentage.format.precision causes error because it is a String, not a Fixnum

### ISSUE THREAD

**Issue by florianguenther** [solidusio-contrib/solidus_i18n#60]
in file `config/locales/de.yml`

```
number:
  percentage:
    format:
      precision: '1'
```

should be changed to

```
number:
  percentage:
    format:
      precision: 1
```
